name: "Update Editor's Copy"

on:
  push:
    paths-ignore:
    - README.md
    - CONTRIBUTING.md
    - LICENSE.md
    - .gitignore
  pull_request:
    paths-ignore:
    - README.md
    - CONTRIBUTING.md
    - LICENSE.md
    - .gitignore

jobs:
  build:
    name: "Update Editor's Copy"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: "Setup"
      id: setup
      run: date -u "+date=%FT%T" >>"$GITHUB_OUTPUT"

    - name: "Caching"
      uses: actions/cache@v4
      with:
        path: |
          .refcache
          .venv
          .gems
          node_modules
          .targets.mk
        key: i-d-${{ steps.setup.outputs.date }}
        restore-keys: i-d-

    - name: "Setup Python"
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: "Setup Ruby"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3"
        bundler-cache: false

    - name: "Setup Node"
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: "Build Drafts"
      run: make all

    - name: "Update GitHub Pages"
      if: ${{ github.event_name == 'push' }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: make gh-pages

    - name: "Archive Built Drafts"
      uses: actions/upload-artifact@v4
      with:
        path: |
          draft-*.html
          draft-*.txt
